### ISSUE TITLE
Cant seem to find the vue-front module

### ISSUE THREAD

**Issue by NikoDyring** [IsraelDCastro/rails-api-template#1]
Hello my friend; I appreciate the effort of making this repo. I just stumbled upon Primevue and wanted to test your solution out, but I'm running into the following issue (see the image attached)

I've tried both doing it with the remote github call, and cloning the repository, it does the same error either way. 

![image](https://github.com/user-attachments/assets/834adcab-ab04-4017-ae45-7d985b2fb500)

**Comment by IsraelDCastro** [comment]
Hi, I'll take the time to check the issue and try to fix it. I think I forgot to finish the project, or at least the first part of it.

**Comment by IsraelDCastro** [comment]
Hello @NikoDyring , I fixed the problem. I hadn't finished the first part of the project.

**Comment by NikoDyring** [comment]
Cool! I'll try it out ;)
